### ISSUE TITLE
Add quick start guide to README

### ISSUE THREAD

**Issue by cisaacstern** [leap-stc/ClimSim#22]
A primary action item from today's meeting was adding a clearly-defined quick start guide to this repo. The README serves as the primary documentation so that is probably the right place for it. Thanks @tz33cu for this helpful suggestion.

**Comment by NoraLoose** [comment]
What do people think about outsourcing some of the stuff in the README to the website, where the latter could then serve as the primary documentation. The quick start guide could then also be part of the website, and we could link to it from the README.

**Comment by cisaacstern** [comment]
I think quick start should be concise and would be a high priority item to keep near the top of the README (and duplicated on the website), as this is the one piece of information we want to make sure people find. I agree that more detailed info (tables, detailed preprocessing instructions, etc.) on the website makes sense.

**Comment by NoraLoose** [comment]
I think we can close this because @jerrylin96 has added this via [this commit](https://github.com/leap-stc/ClimSim/commit/d90e0e1c4c05c10663fbcbf3b9d1a52e46473678). Jerry, now that we are several people managing the GitHub repo, it would be great if you could submit PRs (rather than pushing directly to the main branch) so we can keep track of what is happening. :) Thanks so much!
