### ISSUE TITLE
Why use ncol as dimension instead of lat,lon

### ISSUE THREAD

**Issue by aperezvelasco** [leap-stc/ClimSim#71]
Hi,

Could somebody give me some background of why only one spatial dimension (ncol) is used to define the spatial structure instead of two spatial dimensions (lat, lon) as is done in the standard way?

What benefits are associated with it?

Thanks beforehand for your responses!

**Comment by NoraLoose** [comment]
Thanks for reaching out @aperezvelasco! 

I am tagging @sungdukyu as he will be the right person to answer your questions.

**Comment by jerrylin96** [comment]
Hello @aperezvelasco! Apologies for the delayed response. The spatial dimension is ncol and not lat, lon because E3SM-MMF uses a spectral element grid.

https://e3sm.org/improving-clouds-in-e3sm-with-a-multi-scale-modeling-framework/

https://en.wikipedia.org/wiki/Spectral_element_method

Happy holidays!

**Comment by NoraLoose** [comment]
Hi @aperezvelasco, does this answer your question? Please feel free to reopen this issue if not. Thanks for your answer @jerrylin96!

**Comment by aperezvelasco** [comment]
It solved it! Many thanks!
